### ISSUE TITLE
Hope to upload Gerbers to Advanced PCB

### ISSUE THREAD

**Issue by theBillLee** [HDR/Gameboy-Camera-Flashcart#2]
Now BCPWay only has Standard PCB, hope to upload Gerbers to Advanced PCB Thanks

**Comment by HDR** [comment]
![image](https://user-images.githubusercontent.com/20230450/174514986-c2348236-10e9-4e63-aae2-7dd714bf62b3.png)

**Comment by theBillLee** [comment]
I didn't make that clear. I know it's available at PCBWay. But PCBWay's is Standard PCB, I hope you can upload to PCBWay Advanced PCB. not hope you upload to Github

**Comment by HDR** [comment]
Ah gotcha, i've put up an advanced version here https://www.pcbway.com/project/shareproject/Game_Boy_Camera_Flashcart_2x1MB_FRAM_Advanced_PCB_73cba77a.html
